plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
	maven {
		url "https://pkgs.dev.azure.com/djtheredstoner/DevAuth/_packaging/public/maven/v1"
	}
	maven {
		url = "https://maven.isxander.dev/releases"
	}
}

loom {
	splitEnvironmentSourceSets()

	mods {
		"bomboaddons" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}

	runs {
		client {
			client()
			ideConfigGenerated(true)
			name("Minecraft Client")
			source(sourceSets.main)
			source(sourceSets.client)
			vmArg("-Xmx4G")
			vmArg("-XX:+UseG1GC")
			property("devauth.enabled", "true")
			property("devauth.account", "main")
		}
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"

	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
	implementation "net.fabricmc:fabric-language-kotlin:1.13.1+kotlin.2.1.10"
	runtimeOnly "me.djtheredstoner:DevAuth-fabric:1.2.2"
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": inputs.properties.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
	it.options.encoding = "UTF-8"
	it.options.incremental = true
	it.options.fork = false
}

compileJava.enabled = false

java {
	withSourcesJar()

	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
}

jar {
	inputs.property "archivesName", project.base.archivesName
	duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.named('sourcesJar', Jar) {
	duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

publishing {
	publications {
		create("mavenJava", MavenPublication) {
			artifactId = project.archives_base_name
			from components.java
		}
	}
}
